### ISSUE TITLE
net::ERR_INCOMPLETE_CHUNKED_ENCODING

### ISSUE THREAD

**Issue by 798523** [UNIZAR-30246-WebEngineering/lab1-git-race#27]
Hello, I'm trying to get a response from an endpoint. However, I can't solve the problem that appears in my console. I show it down below:

![image](https://user-images.githubusercontent.com/99818380/194523973-c316ec71-d2c7-4f4b-af3b-1fa2533a6610.png)

For the request, I'm using JS with Axios:

![image](https://user-images.githubusercontent.com/99818380/194524449-268913c0-f442-44b3-ab7b-61011a366e0e.png)

I guess the request is correctly processed, but the response can't be encoded the good way.

I attach also the function at the endpoint:

![image](https://user-images.githubusercontent.com/99818380/194524850-ea6bfe31-3979-4e35-8fad-f5f25de3e6c6.png)

That function is inside a class with type RestController, so we can return a response.

Don't know how to solve it. Please send help.

**Comment by fjlopez** [comment]
This error code is raised when the user doesn’t receive the final 0-length chunk of a chunked transfer. When it happens, website pages hang or fail to load correctly, and Google Chrome displays a blank page. It’s important to understand that this problem usually occurs with users using Google Chrome when prefeteching is enabled, an agressive antivirus software is performing network real-time protection, or some Chrome extensions are interfering.

How to verify if the culprit is Chrome: Test the application with Firefox.

**Comment by fjlopez** [comment]
@798523 did you test the application with Firefox?

**Comment by 798523** [comment]
No I didn't. I don't know why but that error with Chrome didn't reappear.

**Comment by fjlopez** [comment]
This is a random error. Nevertheless, warn me if it happens again. I think that we can close this issue by now.
