### ISSUE TITLE
SonarQube fails in pull request builds

### ISSUE THREAD

**Issue by RecuencoJones** [UNIZAR-30246-WebEngineering/lab1-git-race#39]
SonarQube runs with the given token and fails for pull requests, causing the build to fail and pull requests unable to be merged.

@SAReyes please try to find a fix for this.

**Comment by SAReyes** [comment]
The builds are failing on pull requests from a forked repo, we managed to replicate the same behaviour on one of our [repos](https://github.com/PistachoSoft/dummy-calculator), it seems like a permission issue but I can't find a quick solution for it.

By the way, I've opened a [question](http://stackoverflow.com/questions/39712531/not-authorized-to-execute-any-sonarqube-analysis-when-building-pull-request-from) SO for this as well.

I would appreciate it if someone lends a helping hand.

**Comment by fjlopez** [comment]
I will help you after the BCN conf.

**Comment by SAReyes** [comment]
I've got an [answer](http://stackoverflow.com/a/39720346/4424508) for this. It seems we won't be able to analyse pull requests, it will pollute the sonar project otherwise. This is something the SonarSource team will be working on, it would be a great addition to OSS projects.

I'll update the configuration to run only on master for the time being.
